# Generated by Django 4.2.15 on 2025-12-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="date_of_employement",
            new_name="date_of_employment",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="empoyer_name",
            new_name="employer_name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="passport_nummber",
            new_name="passport_number",
        ),
        migrations.AddConstraint(
            model_name="nextofkin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("profile",),
                name="unique_primary_next_of_kin",
            ),
        ),
    ]
