# Generated by Django 4.2.15 on 2026-01-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_profile",
            "0002_rename_date_of_employement_profile_date_of_employment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("us_dollar", "US Dollar"),
                    ("pound_sterling", "Pound Sterling"),
                    ("ghana_cedis", "Ghana Cedis"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("current", "Current"), ("savings", "Savings")],
                max_length=20,
                null=True,
                verbose_name="Account Type",
            ),
        ),
    ]
